version: "3.8"

services:
  # ---------------------------
  # INFRAESTRUTURA
  # ---------------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: gdash_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    networks:
      - gdash-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: gdash_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - gdash-network

  # ---------------------------
  # APLICAÇÕES
  # ---------------------------

  # API NESTJS
  backend:
    build: ./backend
    container_name: gdash_backend
    ports:
      - "3000:3000"
    # Carrega todo o .env para dentro do container
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - gdash-network

  # WORKER GO
  worker:
    build: ./worker
    container_name: gdash_worker
    env_file:
      - .env
    environment:
      # Sobrescreve variaveis específicas se necessário,
      # ou garante mapeamento correto das que vêm do .env
      RABBITMQ_URL: ${RABBITMQ_INTERNAL_URL}
      QUEUE_NAME: weather_data
      # Comunicação container-to-container usa o nome do serviço 'backend'
      API_URL: http://backend:3000/api/v1/weather/logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    networks:
      - gdash-network

  # COLLECTOR PYTHON
  collector:
    build: ./collector
    container_name: gdash_collector
    env_file:
      - .env
    environment:
      # Passando explicitamente para garantir que o script Python pegue
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBIT_USER}
      RABBITMQ_PASS: ${RABBIT_PASS}
      QUEUE_NAME: weather_data
      LATITUDE: ${LATITUDE}
      LONGITUDE: ${LONGITUDE}
      COLLECT_INTERVAL: ${COLLECT_INTERVAL}
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - gdash-network

  # FRONTEND REACT
  frontend:
    build:
      context: ./frontend
      # Passamos a variavel do .env para o ARG do build do Docker
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: gdash_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - gdash-network

networks:
  gdash-network:
    driver: bridge

volumes:
  mongo_data:
