version: "3.8"

services:
  # --- O NOVO CHEFÃO DA REDE ---
  nginx:
    image: nginx:alpine
    container_name: app_proxy
    restart: always
    ports:
      - "80:80" # Única porta aberta pro mundo!
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

  # --- APLICAÇÕES (Agora escondidas atrás do proxy) ---

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    # ports: REMOVIDO! Ninguém acessa a 3000 direto mais
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: app_frontend
    restart: always
    # ports: REMOVIDO! Ninguém acessa a 5173 direto mais
    env_file:
      - ./frontend/.env
    networks:
      - app_network

  # --- INFRA E WORKERS (Mantém igual) ---

  mongo:
    image: mongo:latest
    container_name: app_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: app_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - app_network

  collector:
    build: ./collector
    container_name: app_collector
    restart: always
    env_file:
      - ./collector/.env
    depends_on:
      - rabbitmq
    networks:
      - app_network

  worker:
    build: ./worker
    container_name: app_worker
    restart: always
    env_file:
      - ./worker/.env
    depends_on:
      - rabbitmq
      - backend
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
